// client/pages/_app.js

import React from 'react';
import "bootstrap/dist/css/bootstrap.min.css";
import Navbar from'../components/Nav';
import Head from 'next/head';
import {ToastContainer} from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { StyleProvider } from '@ant-design/cssinjs';
import '../public/globalcss/styles.css';

interface MyAppProps {
  // Define your component props here
  pageProps: any;
  Component: any;
}

function MyApp({ Component, pageProps } : MyAppProps) {
  return (
    <StyleProvider hashPriority='high'>
    <Head>
      <title>My socialApp</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/images/favicon.png"  />
    </Head>
      <Navbar />
      <ToastContainer position='top-center'/>
      <Component {...pageProps} />
    </StyleProvider>
  );
}

export default MyApp;
