// client/pages/_app.js

import React from 'react';
import "bootstrap/dist/css/bootstrap.min.css";
import Navbar from'../components/Nav';
import Head from 'next/head';

interface MyAppProps {
  // Define your component props here
  pageProps: any;
  Component: any;
}

function MyApp({ Component, pageProps } : MyAppProps) {
  return (
    <div>
    <Head>
      <title>My socialApp</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/images/favicon.png"  />
      <link rel="stylesheet" href="/globalcss/styles.css" />
    </Head>
      <Navbar />
      <Component {...pageProps} />
    </div>
  );
}

export default MyApp;
